### ISSUE TITLE
Feature: Separate order items by station.

### ISSUE THREAD

**Issue by Matando** [ryanmitchell/ti-ext-kitchendisplay#17]
*copy and pasted from the tastyigniter forums to continue discussion here*

Would it be possible to extend the functionality of the extension to separate purchased by kitchen station (ie grill, fryer, etc). I’d like to set up a display by each station so they only see parts of each meal that they need to prepare to keep things flowing efficiently.

A good solution, mentioned by @ryanmitchell on the forums, was to separate the display by meal category. I'm guessing we could do a "?category=<category>" we could do in the url to determine which category we want on the specific display.

**Comment by ryanmitchell** [comment]
I've incorporated this into the version2 branch - feel free to download and test

**Comment by Matando** [comment]
I will check it out. Thank you :)
