### ISSUE TITLE
v2: Access denied on Kitchen View

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-kitchendisplay#20]
Getting Access Denied when attempting to access Kitchen View when logged in as Kitchen user (non admin).

**Comment by ryanmitchell** [comment]
Did you give the user role permission to access the kitchen display extension using the checkbox?

**Comment by roydeanjr** [comment]
Yes, I did. Even tested by removing, that made the menu option disappear. Rechecked the box and tested again, Access Denied.

**Comment by ryanmitchell** [comment]
Ok I’ve pushed a fix - might have been to do with the casing on the permission name.
Let me know if that works.

**Comment by roydeanjr** [comment]
That works perfectly! Thank you!
