### ISSUE TITLE
KD status updates not sending SMS

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-kitchendisplay#23]
Not sure if this is an issue with SMS or with KD, but as of now, SMS will send a test message without a problem, however, KD does not trigger an SMS when the status changes.

I asked Sam and his response is: "Look in SendSmsNotification::triggerAction  and SmsNotify\Controllers\Templates::onTestTemplate  methods to see how the SMS is sent"

**Comment by ryanmitchell** [comment]
We shouldn't need to be doing anything - it should be triggered by the status change.

**Comment by roydeanjr** [comment]
According to all I know and understand, you are correct. However, the planets must not be aligned since I do not ever get a txt msg when I change the status, whether that is via the Order list or KD, not txt msgs ever come through. 

This is the primary reason I was trying to get a development environment set up on my computer; to attempt troubleshooting/stepping through code to try to determine why the sms-notify / notify action is not being triggered. It seems the automation is not functioning. It is like looking for a needle in a haystack and the needle is the same color as they hay!

**Comment by ryanmitchell** [comment]
I would need to know your set up for SMS notify (I dont use it) and what event/rule you are listening on. It would require quite a lot of debugging on my side to be able to figure out.

**Comment by roydeanjr** [comment]
Maybe a screenshare once I get my dev environment going. Thank you.

**Comment by ryanmitchell** [comment]
Took a quick look - are you using the latest version of cart? 
If so, try this fix: https://github.com/ryanmitchell/ti-ext-kitchendisplay/commit/80561526ac323023c46b29246e30de276f2f4f80

**Comment by BreakSecurity** [comment]
As this issue been fixed?

**Comment by ryanmitchell** [comment]
Should be fixed in the next TI release

**Comment by ryanmitchell** [comment]
Closing as we are happy this is a TI core issue
