### ISSUE TITLE
Items that are NOT assigned to a category can't be displayed

### ISSUE THREAD

**Issue by BreakSecurity** [ryanmitchell/ti-ext-kitchendisplay#29]
Category fields is mandatory due to avoid #19 

But in this way items with no category are left out.

Possible fix make category NOT mandatory but check if array is empty in the code.

**Comment by ryanmitchell** [comment]
If your view only wants items from certain categories then it shouldn’t show items with no category. 

Unless I’m misunderstanding your view configuration.

**Comment by BreakSecurity** [comment]
How can I setup no category but all items?

**Comment by ryanmitchell** [comment]
Don’t choose a category in the view?

**Comment by BreakSecurity** [comment]
Yes, but:
![immagine](https://user-images.githubusercontent.com/38836022/101930567-9bee6a00-3bd8-11eb-98bb-547c3ff60fd1.png)

**Comment by BreakSecurity** [comment]
If I force no category by quickly savings the new view (no validation is done on fields if you do quickly but nothing can be perfect :) )


count(): Parameter must be an array or an object that implements Countable
--
in Summary.php line 148

**Comment by ryanmitchell** [comment]
Cool. Will look into both issue next week.

**Comment by BreakSecurity** [comment]
My fix do NOT take in account fields validation stuff (reminder)
