### ISSUE TITLE
Split out permissions to enable manage and view views

### ISSUE THREAD

**Issue by BreakSecurity** [ryanmitchell/ti-ext-kitchendisplay#35]
Split out permissions to enable manage and view views.

**Comment by ryanmitchell** [comment]
Done here: https://github.com/ryanmitchell/ti-ext-kitchendisplay/commit/fa8a2667b65d068c2cc71255ba76f875532138da

**Comment by BreakSecurity** [comment]
Amazing should we have a new release? ;)
