### ISSUE TITLE
Feature Request - Add ability to show just current day

### ISSUE THREAD

**Issue by Zelig880** [ryanmitchell/ti-ext-kitchendisplay#38]
As an user of the Kitchen Display, I would like to have the ability to set the display to just show todays date (or if possible select max days since order), so that the display would just show orders that need to be prepared straight away, or if not possible show the date on the actual cards.

Extra info: One of my customer has mentioned that she has allowed people to pre-order, and the kitchen display is showing orders that are a couple of days away. If the above is not possible, then we should make sure the DATE or the order is shown on the kitchen cards.

Possible features implementation
- Add a new field in the settings to enable if to show current day only
- Add a new field in the settings to enable the customer to select NUMBER of days since the order need to be fulfilled (dropdown in days)
- Add Information within the Display cards to actually show the date (as well as the times)
- Add few more entries within the configuration of the second line to also allow for DATE to be seen instead than just time

**Comment by ryanmitchell** [comment]
Sounds like a great idea. Would you be willing to work on a PR for it?

I would suggest:
> Add a new field in the settings to enable if to show current day only

And also 
> Add few more entries within the configuration of the second line to also allow for DATE to be seen instead than just time

As this would allow for good flexibility.

**Comment by Zelig880** [comment]
I have another couple of open source contribution to do, but i I have time I will happily help!

when I "start" to work on it, I will write it on this thread, so if there are no new messages, you can assume that I am NOT working on it.. (in case someone wants to pick it up)

**Comment by BreakSecurity** [comment]
@ryanmitchell 

With last commit now I have weird stuff

00200031Europe/Rome12::Sundayam1212.p12p.27am31Europe/Rome_f2020Sun, 27 Dec 2020 00:00:00 +010012am31 00200031Europe/Rome12::Tuesdaypm127.p07p.313012Europe/Rome_f2020Tue, 29 Dec 2020 19:30:00 +010012pm31

**Comment by ryanmitchell** [comment]
Yep you don’t have the date string in place. It was added in the last beta

**Comment by BreakSecurity** [comment]
I updated and now it works

But I think we should put a warning in the readme saying it

Also is there a way or a string with only day and month because I think that year is a bit too much to display

**Comment by ryanmitchell** [comment]
You can amend the summary file manually or change the Lang string in the admin panel under localisation

**Comment by BreakSecurity** [comment]
Would you accept a PR that amend summary manually? Whit substring or if you have other ideas tell me

**Comment by ryanmitchell** [comment]
You are best to amend the language string - thats the ‘right’ way to change it

**Comment by BreakSecurity** [comment]
Done #46 and tested @Zelig880 can you close this?
