### ISSUE TITLE
v2.0.5: Cards Tab Incorrect Time/Phone/Total/PayCode and Phone/Time....

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-kitchendisplay#39]
The Time/Phone/Total/PayCode and Phone/Time.... selections actually show the opposite on the card. Each name shows the other's card data.

![image](https://user-images.githubusercontent.com/36243458/103217477-4a372680-48de-11eb-8b25-c21ea628f701.png)
vs

![image](https://user-images.githubusercontent.com/36243458/103217596-92564900-48de-11eb-8b2d-40b7ef62277c.png)

**Comment by ryanmitchell** [comment]
Thanks - can you work on a fix?

**Comment by roydeanjr** [comment]
Yes.

**Comment by ryanmitchell** [comment]
Thank you!
