### ISSUE TITLE
View name showed on top of view

### ISSUE THREAD

**Issue by liffez** [ryanmitchell/ti-ext-kitchendisplay#43]
If you have more than one view it would be great if the name of the view is displayed at the top of screen somewhere

**Comment by ryanmitchell** [comment]
Yep - feel free to open a PR ;)

**Comment by liffez** [comment]
I Will try to see how I can do that.

**Comment by BreakSecurity** [comment]
@liffez please review

**Comment by liffez** [comment]
Wow - this works great, thanks alot
