### ISSUE TITLE
Not able to change status in kitchen view

### ISSUE THREAD

**Issue by g1lby** [ryanmitchell/ti-ext-kitchendisplay#44]
Hi,
I'm new to your extension as well as to TI, however I'm loving it so far.
I've placed test orders and am unable to change the status of an order within the view screen.
When clicking on Prep, Ready or Completed, nothing happens. Did I forget to configure something or is there an open issue with this function?

Cheers
g1lby

**Comment by ryanmitchell** [comment]
Hello

There are no issues I’m aware of.

You need to assign prep, ready and completed to the statuses you want to change to. See my button config attached.

**Comment by g1lby** [comment]
Got it, thanks for the lightning-fast help :)
