### ISSUE TITLE
Add a function

### ISSUE THREAD

**Issue by Cenzi96** [ryanmitchell/ti-ext-kitchendisplay#51]
Hi, I wanted to ask for an update of the extension, I give an example, if I order a pizza with salami but without tomato, from the kitchen displey you cannot see what must be added and what must be removed from the pizza because the option name does not come out of the added object

**Comment by ryanmitchell** [comment]
I would accept a PR for it if you wanted to work on it?

**Comment by Cenzi96** [comment]
Sorry but I didn't understand, what does pr mean? I don't speak English well and I can't understand the meaning of this abbreviation

**Comment by Cenzi96** [comment]
okay

**Comment by BreakSecurity** [comment]
I didn't understand what you want can you share some screens?

**Comment by Cenzi96** [comment]
![github](https://user-images.githubusercontent.com/81419264/114289565-3f616580-9a79-11eb-9948-6bdf210d9cd3.png)


> I didn't understand what you want can you share some screens?

**Comment by BreakSecurity** [comment]
Got it. Right now ti do not support negative prices or remove of single options from the set of basic ingradients. As you have done you can put a + and a - in front of name options and nothing more. By the way it's not something that regards directly kd. If you feel it would be a nice core additions feel free to open a pr on tasty repo to be discussed

**Comment by Cenzi96** [comment]
I intend to insert only the words WITH and WITHOUT, or if the ingredient is in the category WITH write WITH on the kitchen display if the ingredient is part of the item WITHOUT write without.
if i was selling t-shirts i should say TYPE: wool
Size: xs

**Comment by ryanmitchell** [comment]
Should be added here:
https://github.com/ryanmitchell/ti-ext-kitchendisplay/commits/master
