### ISSUE TITLE
Newest first

### ISSUE THREAD

**Issue by hozakjaf** [ryanmitchell/ti-ext-kitchendisplay#52]
Hi!

Thanks for the amazing plugin. I just want to know how I can show the newest first on top. Right now the newest are shown at the bottom. Can I implement an Order by date function somewhere in the code?

I hope you can help!

With kind regards,
Hozak

**Comment by ryanmitchell** [comment]
It currently orders them by the next that needs to be made... as in the next priority for the kitchen.

You can see the orderBy clauses here:
https://github.com/ryanmitchell/ti-ext-kitchendisplay/blob/6a3d8aebd29f26e0b4e9cf67013865bf31b8357d/controllers/Summary.php#L137

Just be aware that any changes may be overwritten by updates.
