### ISSUE TITLE
Displays only the first X orders in 'Number of orders to show'

### ISSUE THREAD

**Issue by Tanbir17** [ryanmitchell/ti-ext-kitchendisplay#54]
**Expected behavior:**
Display the latest X orders

**Actual behavior:**
Displays the first X orders

**Reproduce steps:**
Set the number of orders to show to a number less than the amount you have and it will only show from the first ones instead of the latest ones.

**Version:**
Latest

**Comment by ryanmitchell** [comment]
This is expected behaviour as it orders by order date and time, so it should show the next orders that need fulfilled by the kitchen.

If you feel its wrong, please provide a worked example with screenshots to help understand the issue.
