### ISSUE TITLE
Cards compress too small

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-kitchendisplay#8]
Just noticed that the cards are compressing too narrow when thee are not enough to fill a page. check out the image: 
![image](https://user-images.githubusercontent.com/36243458/93005819-83f44500-f51a-11ea-90e9-b7f192d5ecc8.png)

**Comment by ryanmitchell** [comment]
Try replacing the "col col-sm-6 col-lg-4 mb-4” with “col” in the view and let me know how that works for you across various screen sizes.

**Comment by roydeanjr** [comment]
Works best with this `col col-sm-auto col-lg-auto mb-3`. Thank you! I'll create a PR as I added some code to the view to add a `<br/>` after an item that has no options.
